### ISSUE TITLE
Init Sumo Logic pipe handler metrics support

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-sumologic-handler#1]
Requirements: 

- Send metrics to a Sumo Logic HTTP Source ([docs](https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Metrics-to-an-HTTP-Source)) 
  - Must set `Content-Type` header to one of: 
    - `application/vnd.sumologic.prometheus` 
    - `application/vnd.sumologic.graphite`
    - `application/vnd.sumologic.carbon2`
- Sends multiple metrics in a single payload ([docs](https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Metrics-to-an-HTTP-Source#sending-multiple-metrics-in-a-single-payload))
- Handler config flags (and [corresponding HTTP headers](https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Metrics-to-an-HTTP-Source#supported-http-headers)): 
  - `--format` == `Content-Type: application/vnd.sumologic.<format>` (`prometheus`, `graphite`, or `carbon2`)
  - `--source-url` == HTTP Source URL where the handler will send metrics
  - `--source-name` == `X-Sumo-Name: <source-name>` (Sumo Logic "desired source name")
  - `--source-host` == `X-Sumo-Host: <source-host>` 
  - `--source-category` == `X-Sumo-Category: <source-category>` 
  - `--dimensions` == `X-Sumo-Dimensions: <dimensions` (comma separated list of key=value pairs, one pair per "dimension" to apply to every metric)
  - `--metadata` == `X-Sumo-Metadata: <metadata>` (comma separated list of key=value pairs, one pair per "metadata" property to apply to every metric)

Notes: 

- Support for sending Sensu events to an HTTP source is out of scope for the initial implementation
- GZip compression is out of scope for the initial implementation

**Comment by jspaleta** [comment]
Initial Release is cut. Closing
